const db = [
  {
    id: 1,
    name: "Mais um gol",
    brand: "Volkswagen",
    model: "206",
    year: "2010",
    km: 30000,
    color: "black",
    city: "Vitória",
    state: "ES",
    value: 40000,
    imageLink: require("./carImages/peugeot-206.jpg"),
  },
  {
    id: 2,
    name: "Golzinho bonitinho",
    brand: "Volkswagen",
    model: "206",
    year: "2010",
    km: 30000,
    color: "black",
    city: "Vitória",
    state: "ES",
    value: 40000,
    imageLink: require("./carImages/peugeot-206.jpg"),
  },
  {
    id: 3,
    name: "peugeo25",
    brand: "peugeot",
    model: "206",
    year: "2010",
    km: 30000,
    color: "black",
    city: "Vitória",
    state: "ES",
    value: 5000,
    imageLink: require("./carImages/peugeot-206.jpg"),
  },
  {
    id: 4,
    name: "Gol",
    brand: "Volkswagen",
    model: "206",
    year: "2010",
    km: 30000,
    color: "black",
    city: "Vitória",
    state: "ES",
    value: 35417,
    imageLink: require("./carImages/peugeot-206.jpg"),
  },
  {
    id: 5,
    name: "carro",
    brand: "marca",
    model: "206",
    year: "2010",
    km: 30000,
    color: "black",
    city: "Vitória",
    state: "ES",
    value: 35417,
    imageLink: require("./carImages/peugeot-206.jpg"),
  },
  {
    id: 6,
    name: "carro2",
    brand: "marca2",
    model: "206",
    year: "2010",
    km: 30000,
    color: "black",
    city: "Vitória",
    state: "ES",
    value: 35417,
    imageLink: require("./carImages/peugeot-206.jpg"),
  },
  {
    id: 7,
    name: "carro5",
    brand: "marca5",
    model: "206",
    year: "2010",
    km: 30000,
    color: "black",
    city: "Vitória",
    state: "ES",
    value: 35417,
    imageLink: require("./carImages/peugeot-206.jpg"),
  },
];


export default db;